# Generated by Django 3.1.1 on 2023-06-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20230627_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='id_detalle_venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ManyToManyField(to='personas.Combo'),
        ),
    ]
