# Generated by Django 3.1.1 on 2023-07-08 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20230627_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id_combo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='personas.combo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='id_detalle_venta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='personas.detalleventa'),
            preserve_default=False,
        ),
    ]
